title: renxc's page
description: renxc's page
name_pinyin: REN Xuancheng
name_chinese: 任宣丞
theme: jekyll-theme-minimal
email: renxc@pku.edu.cn
email_full: mailto:renxc@pku.edu.cn
aff1: Institute of Computational Linguistics,
aff1url: http://icl.pku.edu.cn/
aff2: School of Electronics Engineering and Computer Science,
aff2url: http://eecs.pku.edu.cn/
aff3: Peking University
aff3url: http://www.pku.edu.cn/
aff4: LANCO,
aff4url: http://lanco.pku.edu.cn/
