title: pkuzzy's page
description: pkuzzy's page
name_pinyin: Zhiyuan Zhang
name_chinese: 张之远
theme: jekyll-theme-minimal
email: zzy1210@pku.edu.cn
email_full: mailto:zzy1210@pku.edu.cn
aff2: School of Computer Science
aff2url: https://cs.pku.edu.cn/index.htm
aff3: Peking University
aff3url: https://www.pku.edu.cn/
aff4: LANCO Lab
aff4url: https://lancopku.github.io//
